In [2]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:', array1.shape)
print('array1 차원:', array1.ndim)

array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:', array2.shape)
print('array2 차원:', array2.ndim)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:', array3.shape)
print('array3 차원:', array3.ndim)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array1 차원: 1
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array2 차원: 2
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array3 차원: 2


In [3]:
list1 = [1,2,'명환']
array1 = np.array(list1)
print(array1, array1.dtype)

list2 = [1,2,3.0]
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' '명환'] <U11
[1. 2. 3.] float64


In [13]:
x = np.arange(12)
y = x.reshape(3, 4)

print('x = ',x)
print('\n|   |   |   |\n reshape(3,4)\n|   |   |   |\nV   V   V   V\n')
print('y = ',y)

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11]

|   |   |   |
 reshape(3,4)
|   |   |   |
V   V   V   V

y =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
a = x.reshape(-1, 2)
b = x.reshape(-1, 4)

print('a =')
print(a)
print('')
print('b =')
print(b)

a =
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

b =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
x9 = np.arange(9)
x33 =  x9.reshape(-1,3)
print(x33[2])
print(x33[2:,:])

[6 7 8]
[[6 7 8]]


In [24]:
array1d = np.arange(start=1, stop=10)
print('array1d : ',array1d)

array2 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array2)

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

array1d :  [1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]
불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


In [26]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
print('')
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
print('')
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)
org_array = np.array([ 3, 1, 9, 5])
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

원본 행렬: [3 1 9 5]

np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]

org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [27]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [28]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


# 1차원 list와 ndarray → DataFrame 변환

In [30]:
import pandas as pd

col_name1=['col1']    # 컬럼명
list1 = [1, 2, 3]    # 1차원 리스트
array1 = np.array(list1)    # 1차원 ndarray

print('array1 shape:', array1.shape )

df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


# 2차원 list와 ndarray → DataFrame 변환

In [31]:
# 3개의 컬럼명이 필요 (3열 이므로)
col_name2=['col1', 'col2', 'col3']

# 2행x3열 형태의 리스트 생성
list2 = [[1, 2, 3],
         [11, 12, 13]]

array2 = np.array(list2)    # 2행x3열 형태의 ndarray 생성
print('array2 shape:', array2.shape )

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)

df_array1 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array1)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


# dict → DataFrame 변환

In [32]:
# Key는 컬럼명으로 매핑
# Value는 리스트 형(또는 ndarray)
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [33]:
# DataFrame을 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3))
print('df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'>
df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [34]:
# DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}
